#    zipkin服务地址
spring:
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
#        采集率
      percentage: 1.0

# fescar 事务组名字
  cloud:
    alibaba:
      seata:
        tx-service-group: tx_group

# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
