#    zipkin服务地址
spring:
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
#        采集率
      percentage: 1.0

# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.1:8761/eureka,http://192.168.0.2:8761/eureka,http://192.168.0.3:8761/eureka